- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/npm-packages.yml
#    - include: tasks/zsh-setup.yml
#    - include: tasks/slack-setup.yml
#    - include: tasks/personal-projects.yml
#    - include: tasks/nvim-setup.yml
#    - include: tasks/brave.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/chrome.yml

