- name: Installing stow
  apt: name=stow
  tags: &tags_for_dotfiles_tasks [ 'Install', 'Dotfiles', 'Stow']

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/joey-dev/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: *tags_for_dotfiles_tasks

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu_update
  tags: *tags_for_dotfiles_tasks

