- name: Install eslint
  npm:
    name: eslint
    global: yes
  tags: &tags_for_node_tasks [ 'Install', 'Node' ]
  
- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags: *tags_for_node_tasks

- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags: *tags_for_node_tasks

