- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: yes
  tags: &tags_for_zsh_tasks [ 'Install', 'Productivity', 'Dotfiles', 'Zsh' ]

- name: Oh-My-Zsh
  #shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  tags: 'not_working'
  become: yes

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: &tags_for_zsh_tasks_plugins [ 'Zsh', 'Zsh_plugins' ]

- name: Install zsh-auto-notify
  ansible.builtin.git:
    repo: 'https://github.com/MichaelAquilina/zsh-auto-notify.git'
    dest: "~/.oh-my-zsh/plugins/auto-notify"
  tags: *tags_for_zsh_tasks_plugins

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags: *tags_for_zsh_tasks_plugins

